# itertools

###### combination

In [2]:
import itertools

bins = [1, 2, 3]
seq_length = 3
list(itertools.combinations(bins, seq_length))

[(1, 2, 3)]

###### combination with replacement

In [5]:
import itertools

bins = [1, 2, 3]
seq_length = 3
list(itertools.combinations_with_replacement(bins, seq_length))

[(1, 1, 1),
 (1, 1, 2),
 (1, 1, 3),
 (1, 2, 2),
 (1, 2, 3),
 (1, 3, 3),
 (2, 2, 2),
 (2, 2, 3),
 (2, 3, 3),
 (3, 3, 3)]

###### permutations

In [4]:
import itertools

bins = [1, 2, 3]
seq_length = 3
list(itertools.permutations(bins, seq_length))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]

###### Cartesian product

In [6]:
import itertools
x = [1, 2, 3, 4, 5, 6]

[p for p in itertools.product(x, repeat=6)]

[(1, 1, 1, 1, 1, 1),
 (1, 1, 1, 1, 1, 2),
 (1, 1, 1, 1, 1, 3),
 (1, 1, 1, 1, 1, 4),
 (1, 1, 1, 1, 1, 5),
 (1, 1, 1, 1, 1, 6),
 (1, 1, 1, 1, 2, 1),
 (1, 1, 1, 1, 2, 2),
 (1, 1, 1, 1, 2, 3),
 (1, 1, 1, 1, 2, 4),
 (1, 1, 1, 1, 2, 5),
 (1, 1, 1, 1, 2, 6),
 (1, 1, 1, 1, 3, 1),
 (1, 1, 1, 1, 3, 2),
 (1, 1, 1, 1, 3, 3),
 (1, 1, 1, 1, 3, 4),
 (1, 1, 1, 1, 3, 5),
 (1, 1, 1, 1, 3, 6),
 (1, 1, 1, 1, 4, 1),
 (1, 1, 1, 1, 4, 2),
 (1, 1, 1, 1, 4, 3),
 (1, 1, 1, 1, 4, 4),
 (1, 1, 1, 1, 4, 5),
 (1, 1, 1, 1, 4, 6),
 (1, 1, 1, 1, 5, 1),
 (1, 1, 1, 1, 5, 2),
 (1, 1, 1, 1, 5, 3),
 (1, 1, 1, 1, 5, 4),
 (1, 1, 1, 1, 5, 5),
 (1, 1, 1, 1, 5, 6),
 (1, 1, 1, 1, 6, 1),
 (1, 1, 1, 1, 6, 2),
 (1, 1, 1, 1, 6, 3),
 (1, 1, 1, 1, 6, 4),
 (1, 1, 1, 1, 6, 5),
 (1, 1, 1, 1, 6, 6),
 (1, 1, 1, 2, 1, 1),
 (1, 1, 1, 2, 1, 2),
 (1, 1, 1, 2, 1, 3),
 (1, 1, 1, 2, 1, 4),
 (1, 1, 1, 2, 1, 5),
 (1, 1, 1, 2, 1, 6),
 (1, 1, 1, 2, 2, 1),
 (1, 1, 1, 2, 2, 2),
 (1, 1, 1, 2, 2, 3),
 (1, 1, 1, 2, 2, 4),
 (1, 1, 1, 2, 2, 5),
 (1, 1, 1, 2,

### Generating number sequence

###### using built-in
> Refer to
> [https://docs.python.org/3/library/stdtypes.html#typesseq-range]

In [2]:
list(range(1,4))

[1, 2, 3]

In [3]:
num = list(range(1,4))
[str(i) for i in num]

['1', '2', '3']

In [6]:
# u can use plus(+) operator to concate two list.
[ 'I' + str(i) for i in list(range(1,3))] + [ 'C' + str(i) for i in list(range(1,5))]

['I1', 'I2', 'C1', 'C2', 'C3', 'C4']

###### manually creating Numpy array

In [7]:
np.array([1,2,3,4,5,6,7])

array([1, 2, 3, 4, 5, 6, 7])

###### using Numpy **arange**
> Refre to [http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.arange.html]

In [2]:
import numpy as np
np.arange(start=10, stop=3, step=-1, dtype='int32')

array([10,  9,  8,  7,  6,  5,  4])

In [4]:
np.arange(1, 10, 2) # 1부터 10까지 2식 증가

array([1, 3, 5, 7, 9])

In [5]:
# or simply
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

###### using Numpy linspace
> Refer to [http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linspace.html#numpy.linspace]

In [6]:
import numpy as np
np.linspace(start=1, stop=10, num=7, endpoint=True, retstep=False, dtype=None)

array([  1. ,   2.5,   4. ,   5.5,   7. ,   8.5,  10. ])

In [7]:
# or simply
np.linspace(1, 10, 7) # 1부터 10까지 7개로 나눔

array([  1. ,   2.5,   4. ,   5.5,   7. ,   8.5,  10. ])

###### using r__ or c__function


> r\_ : row-wise concatenation  
> c\_ : column-wise

In [18]:
np.r_[1, 3:6, 10]

array([ 1,  3,  4,  5, 10])

In [20]:
np.c_[1:2, 3:4, 10:11]

array([[ 1,  3, 10]])

### Using NaN

In [1]:
import numpy as np
np.nan

nan

### Static Random Numbers

In [2]:
import numpy as np
rs = np.random.RandomState(123)
X = rs.multinomial(3, [1/9.]*9, size=30)
X

array([[0, 0, 0, 0, 1, 0, 2, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 1],
       [1, 0, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 2],
       [1, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 2, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 1, 1, 0, 0, 0, 1, 0],
       [1, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 2, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 1],
       [2, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 2, 0],
       [1, 0, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0,

In [6]:
np.random.binomial(1, 0.5)

0

###### Random from standard normal

In [1]:
import numpy as np
np.random.randn(3, 4)

array([[ 0.32962674,  0.19715432,  0.32658998, -0.10715919],
       [-0.79591969, -0.17419052,  0.30035533, -1.46735591],
       [-0.91287007,  0.29660634, -0.13472205, -0.12262614]])

###### Random from uniform [0, 1]

In [2]:
import numpy as np
np.random.rand(3, 4)

array([[ 0.20985622,  0.86409066,  0.43936346,  0.36958792],
       [ 0.45777016,  0.21163789,  0.72088758,  0.99011846],
       [ 0.00746735,  0.46189542,  0.98280776,  0.84188483]])